# Configures appc tests at Travis CI (https://travis-ci.org).

language: go

matrix:
  include:
    - go: 1.5.3
      env: GO15VENDOREXPERIMENT=1
    - go: 1.6.2

# Stop Travis mucking about with godeps:
# https://docs.travis-ci.com/user/languages/go#godep-support
install: true

script:
 - ./test
